type: history-graph
hours_to_show: 12
entities:
  - entity: sensor.temperature_158d000465830c
    name: Гостиная
  - entity: sensor.temperature_158d00049dbfda
    name: Санузел
  - entity: sensor.temperature_158d00049dc2ee
    name: Спальня
  - entity: sensor.humidity_158d000465830c
    name: Гостиная
  - entity: sensor.humidity_158d00049dbfda
    name: Санузел
  - entity: sensor.humidity_158d00049dc2ee
    name: Спальня
  - entity: sensor.0x04cf8cdf3c8033c1_power
    name: Конвектор
