type: glance
columns: 5
entities:
  - entity: sensor.temperature_158d000465830c
    name: Гостиная
    icon: mdi:thermometer
  - entity: sensor.0x04cf8cdf3c8033c1_power
    name: Конвектор
  - entity: sensor.temperature_158d00049dbfda
    name: Санузел
    icon: mdi:thermometer
  - entity: sensor.temperature_158d00049dc2ee
    name: Спальня
    icon: mdi:thermometer
  - entity: sensor.temperature_158d00049fe048
    name: Улица
    icon: mdi:thermometer
  - entity: sensor.humidity_158d000465830c
    name: ""
    icon: mdi:water-percent
  - entity: sensor.0x04cf8cdf3c8033c1_energy
    name: ""
  - entity: sensor.humidity_158d00049dbfda
    name: ""
    icon: mdi:water-percent
  - entity: sensor.humidity_158d00049dc2ee
    name: ""
    icon: mdi:water-percent
  - entity: sensor.humidity_158d00049fe048
    name: ""
    icon: mdi:water-percent