type: entity-filter
entities:
  - light.megad1_p7
  - light.megad1_p8
  - light.megad1_p9
  - light.megad1_p10
  - light.megad1_p11
  - light.megad1_p12
  - light.megad1_p13
  - light.megad1_p22
  - light.megad1_p23
#  - light.megad1_p24
  - light.megad1_p25
  - light.megad1_p26
  - light.megad1_p27
  - light.megad1_p28
  - light.megad2_p7
#  - light.megad2_p8
  - light.megad2_p9
  - light.megad2_p10
  - light.megad2_p11
  - light.megad2_p12
  - light.megad2_p13
  - light.megad2_p22
  - light.megad2_p23
  - light.megad2_p24
  - light.megad2_p25
  - light.megad2_p26
  - light.megad2_p27
  - light.megad2_p28
  - entity: light.yeelight_bslamp2_0x000000001263baec
    name: Лампа
    icon: mdi:lamp
state_filter:
  - "on"