  - id: Обновление статусов MegaD
    alias: megad_refresh
    trigger:
      - platform: time_pattern
        seconds: "/20"
      - platform: event
        event_type: megad_refresh
    action:
      - service: downloader.download_file
        data_template:
          url: "http://192.168.0.141/sec/?cmd=all"
          filename: "megad1.txt"
          overwrite: "true"
      - service: downloader.download_file
        data_template:
          url: "http://192.168.0.142/sec/?cmd=all"
          filename: "megad2.txt"
          overwrite: "true"
  - alias: door_sensor_on
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d00044d56f1
      from: 'off'
      to: 'on'
    action:
      service: light.turn_on
      data:
        entity_id:
          - light.megad1_p7
          - light.megad1_p25

  - alias: slack_notification
    trigger:
      - platform: state
        entity_id: sensor.amber_poslednee_uvedomlenie
    condition:
      condition: state
      entity_id: sensor.amber_poslednee_uvedomlenie
      attribute: package
#      state: org.telegram.messenger
      state: org.Slack
    action:
      service: tts.google_translate_say
      entity_id: media_player.google_home
      data_template:
        message: "Message from {{state_attr('sensor.amber_poslednee_uvedomlenie', 'android.title')}}: {{states('sensor.amber_poslednee_uvedomlenie')}}"
        language: 'en'

  - alias: say_from_text
    trigger:
      - platform: state
        entity_id: input_text.tts_syntesiser
    action:
      service: tts.google_translate_say
      entity_id: media_player.google_home
      data_template:
        message: "{{states('input_text.tts_syntesiser')}}"
        language: 'ru'

  - id: Включить добавление Zigbee
    alias: enable_zigbee_join
    initial_state: true
    trigger:
      platform: state
      entity_id: input_boolean.zigbee_permit_join
      to: 'on'
    action:
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/bridge/config/permit_join
        payload: 'true'
    - service: timer.start
      data:
        entity_id: timer.zigbee_permit_join

  - id: Выключить добавление Zigbee
    alias: disable_zigbee_join
    initial_state: true
    trigger:
    - entity_id: input_boolean.zigbee_permit_join
      platform: state
      to: 'off'
    action:
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/bridge/config/permit_join
        payload: 'false'
    - service: timer.cancel
      data:
        entity_id: timer.zigbee_permit_join

  - id: Выключение по таймеру добавления Zigbee
    alias: disable_zigbee_join_timer
    initial_state: true
    trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.zigbee_permit_join
    action:
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/bridge/config/permit_join
        payload: 'false'
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.zigbee_permit_join

  - id: Включение вентилятора по кнопке около унитаза
    alias: fan_switch
    trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0005785d13
        click_type: single
    action:
    - service: light.toggle
      data:
        entity_id:
          - light.megad2_p24
    - service: light.turn_on
      data:
        entity_id:
          - light.megad2_p13
