  - platform: template
    lights:
      demo_light:
        friendly_name: Demo light
        value_template: "{{ is_state('switch.megad2_p10', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 10
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 10
            mode: 0
      megad1_p7:
        friendly_name: Лента в прихожей
        value_template: "{{ is_state('switch.megad1_p7', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 1
            channel_id: 7
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 1
            channel_id: 7
            mode: 0
      megad1_p8:
        friendly_name: Лента над плитой
        value_template: "{{ is_state('switch.megad1_p8', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 1
            channel_id: 8
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 1
            channel_id: 8
            mode: 0
      megad1_p9:
        friendly_name: Лента в гостиной
        value_template: "{{ is_state('switch.megad1_p9', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 1
            channel_id: 9
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 1
            channel_id: 9
            mode: 0
      megad1_p10:
        friendly_name: Кухня возле плиты
        value_template: "{{ is_state('switch.megad1_p10', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 1
            channel_id: 10
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 1
            channel_id: 10
            mode: 0
      megad1_p12:
        friendly_name: Кухня возле холодильника
        value_template: "{{ is_state('switch.megad1_p12', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 1
            channel_id: 12
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 1
            channel_id: 12
            mode: 0
      megad1_p13:
        friendly_name: Коридор к санузлу
        value_template: "{{ is_state('switch.megad1_p13', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 1
            channel_id: 13
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 1
            channel_id: 13
            mode: 0
      megad1_p22:
        friendly_name: Бра в гостиной
        value_template: "{{ is_state('switch.megad1_p22', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 1
            channel_id: 22
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 1
            channel_id: 22
            mode: 0
      megad1_p23:
        friendly_name: Лента над холодильником
        value_template: "{{ is_state('switch.megad1_p23', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 1
            channel_id: 23
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 1
            channel_id: 23
            mode: 0
#      megad1_p24:
#        friendly_name: Бра над входной дверью
#        value_template: "{{ is_state('switch.megad1_p24', 'on') }}"
#        turn_on:
#        - service: shell_command.megad_trigger_refresh
#          data:
#            entity_id: switch.megad1_p24
#        turn_off:
#        - service: shell_command.megad_trigger_refresh
#          data:
#            entity_id: switch.megad1_p24
      megad1_p25:
        friendly_name: Прихожая
        value_template: "{{ is_state('switch.megad1_p25', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 1
            channel_id: 25
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 1
            channel_id: 25
            mode: 0
      megad1_p27:
        friendly_name: Трековый светильник в гостиной
        value_template: "{{ is_state('switch.megad1_p27', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 1
            channel_id: 27
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 1
            channel_id: 27
            mode: 0
      megad1_p28:
        friendly_name: Обеденный стол
        value_template: "{{ is_state('switch.megad1_p28', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 1
            channel_id: 28
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 1
            channel_id: 28
            mode: 0
      megad2_p7:
        friendly_name: Лента в санузле
        value_template: "{{ is_state('switch.megad2_p7', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 7
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 7
            mode: 0
#      megad2_p8:
#        friendly_name: Бра в лоджии
#        value_template: "{{ is_state('switch.megad2_p8', 'on') }}"
#        turn_on:
#        - service: shell_command.megad_trigger_refresh
#          data:
#            entity_id: switch.megad2_p8
#        turn_off:
#        - service: shell_command.megad_trigger_refresh
#          data:
#            entity_id: switch.megad2_p8
      megad2_p9:
        friendly_name: Лента в спальне
        value_template: "{{ is_state('switch.megad2_p9', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 9
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 9
            mode: 0
      megad2_p10:
        friendly_name: Кабинет
        value_template: "{{ is_state('switch.megad2_p10', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 10
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 10
            mode: 0
      megad2_p12:
        friendly_name: Лоджия
        value_template: "{{ is_state('switch.megad2_p12', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 12
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 12
            mode: 0
      megad2_p13:
        friendly_name: Санузел верхний свет
        value_template: "{{ is_state('switch.megad2_p13', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 13
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 13
            mode: 0
      megad2_p22:
        friendly_name: Гардеробная
        value_template: "{{ is_state('switch.megad2_p22', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 22
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 22
            mode: 0
      megad2_p23:
        friendly_name: Лента в кабинете
        value_template: "{{ is_state('switch.megad2_p23', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 23
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 23
            mode: 0
#      megad2_p23:
#        friendly_name: Лента в кабинете
#        value_template: "{{ is_state('switch.megad2_p23', 'on') }}"
#        turn_on:
#        - service: shell_command.megad_trigger_refresh
#          data:
#            entity_id: switch.megad2_p23
#        turn_off:
#        - service: shell_command.megad_trigger_refresh
#          data:
#            entity_id: switch.megad2_p23
      megad2_p24:
        friendly_name: Вентилятор в санузле
        value_template: "{{ is_state('switch.megad2_p24', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 24
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 24
            mode: 0
      megad2_p25:
        friendly_name: Спальня над кроватью
        value_template: "{{ is_state('switch.megad2_p25', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 25
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 25
            mode: 0
      megad2_p27:
        friendly_name: Спальня у окна
        value_template: "{{ is_state('switch.megad2_p27', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 27
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 27
            mode: 0
      megad2_p28:
        friendly_name: Бра в спальне
        value_template: "{{ is_state('switch.megad2_p28', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 28
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 28
            mode: 0
