  - platform: template
    lights:
      demo_light:
        friendly_name: Demo light
        value_template: "{{ is_state('switch.megad2_p10', 'on') }}"
        turn_on:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 10
            mode: 1
        turn_off:
        - service: shell_command.megad_trigger_refresh
          data_template:
            megad_id: 2
            channel_id: 10
            mode: 0
      megad1_p7:
        friendly_name: Лента в прихожей
        value_template: "{{ is_state('switch.megad1_p7', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.megad1_p7
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.megad1_p7
      megad1_p8:
        friendly_name: Лента над плитой
        value_template: "{{ is_state('switch.megad1_p8', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.megad1_p8
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.megad1_p8
      megad1_p9:
        friendly_name: Лента в гостиной
        value_template: "{{ is_state('switch.megad1_p9', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.megad1_p9
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.megad1_p9
      megad1_p10:
        friendly_name: Кухня возле плиты
        value_template: "{{ is_state('switch.megad1_p10', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.megad1_p10
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.megad1_p10
      megad1_p12:
        friendly_name: Кухня возле холодильника
        value_template: "{{ is_state('switch.megad1_p12', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.megad1_p12
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.megad1_p12
      megad1_p13:
        friendly_name: Коридор к санузлу
        value_template: "{{ is_state('switch.megad1_p13', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.megad1_p13
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.megad1_p13
#      megad1_p22:
#        friendly_name: Бра в гостиной
#        value_template: "{{ is_state('switch.megad1_p22', 'on') }}"
#        turn_on:
#        - service: switch.turn_on
#          data:
#            entity_id: switch.megad1_p22
#        turn_off:
#        - service: switch.turn_off
#          data:
#            entity_id: switch.megad1_p22
      megad1_p23:
        friendly_name: Лента над холодильником
        value_template: "{{ is_state('switch.megad1_p23', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.megad1_p23
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.megad1_p23
#      megad1_p24:
#        friendly_name: Бра над входной дверью
#        value_template: "{{ is_state('switch.megad1_p24', 'on') }}"
#        turn_on:
#        - service: switch.turn_on
#          data:
#            entity_id: switch.megad1_p24
#        turn_off:
#        - service: switch.turn_off
#          data:
#            entity_id: switch.megad1_p24
      megad1_p25:
        friendly_name: Прихожая
        value_template: "{{ is_state('switch.megad1_p25', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.megad1_p25
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.megad1_p25
      megad1_p27:
        friendly_name: Трековый светильник в гостиной
        value_template: "{{ is_state('switch.megad1_p27', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.megad1_p27
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.megad1_p27
      megad1_p28:
        friendly_name: Обеденный стол
        value_template: "{{ is_state('switch.megad1_p28', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.megad1_p28
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.megad1_p28
      megad2_p7:
        friendly_name: Лента в санузле
        value_template: "{{ is_state('switch.megad2_p7', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.megad2_p7
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.megad2_p7
#      megad2_p8:
#        friendly_name: Бра в лоджии
#        value_template: "{{ is_state('switch.megad2_p8', 'on') }}"
#        turn_on:
#        - service: switch.turn_on
#          data:
#            entity_id: switch.megad2_p8
#        turn_off:
#        - service: switch.turn_off
#          data:
#            entity_id: switch.megad2_p8
#      megad2_p9:
#        friendly_name: Лента в спальне
#        value_template: "{{ is_state('switch.megad2_p9', 'on') }}"
#        turn_on:
#        - service: switch.turn_on
#          data:
#            entity_id: switch.megad2_p9
#        turn_off:
#        - service: switch.turn_off
#          data:
#            entity_id: switch.megad2_p9
      megad2_p10:
        friendly_name: Кабинет
        value_template: "{{ is_state('switch.megad2_p10', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.megad2_p10
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.megad2_p10
      megad2_p12:
        friendly_name: Лоджия
        value_template: "{{ is_state('switch.megad2_p12', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.megad2_p12
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.megad2_p12
      megad2_p13:
        friendly_name: Санузел верхний свет
        value_template: "{{ is_state('switch.megad2_p13', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.megad2_p13
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.megad2_p13
      megad2_p22:
        friendly_name: Гардеробная
        value_template: "{{ is_state('switch.megad2_p22', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.megad2_p22
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.megad2_p22
#      megad2_p23:
#        friendly_name: Лента в кабинете
#        value_template: "{{ is_state('switch.megad2_p23', 'on') }}"
#        turn_on:
#        - service: switch.turn_on
#          data:
#            entity_id: switch.megad2_p23
#        turn_off:
#        - service: switch.turn_off
#          data:
#            entity_id: switch.megad2_p23
      megad2_p24:
        friendly_name: Вентилятор в санузле
        value_template: "{{ is_state('switch.megad2_p24', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.megad2_p24
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.megad2_p24
      megad2_p25:
        friendly_name: Спальня над кроватью
        value_template: "{{ is_state('switch.megad2_p25', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.megad2_p25
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.megad2_p25
      megad2_p27:
        friendly_name: Спальня у окна
        value_template: "{{ is_state('switch.megad2_p27', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.megad2_p27
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.megad2_p27
#      megad2_p28:
#        friendly_name: Бра в спальне
#        value_template: "{{ is_state('switch.megad2_p28', 'on') }}"
#        turn_on:
#        - service: switch.turn_on
#          data:
#            entity_id: switch.megad2_p28
#        turn_off:
#        - service: switch.turn_off
#          data:
#            entity_id: switch.megad2_p28
