downloader:
  download_dir: downloads

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
      - type: memory_use_percent
  - platform: mqtt
    name: Bridge state
    state_topic: "zigbee2mqtt/bridge/state"
    icon: mdi:router-wireless

lovelace:
  mode: yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Mosquitto addon https://www.youtube.com/watch?v=9InA6kc6r9s
mqtt:
  broker: core-mosquitto
  discovery: true
  discovery_prefix: homeassistant
  username: mqtt
  password: mqtt

# Text to speech
tts:
  - platform: google_translate

timer: !include config/timer.yaml
input_boolean: !include config/input_boolean.yaml
switch: !include config/switch.yaml
light: !include config/light.yaml
automation: !include config/automation.yaml
shell_command: !include config/shell_command.yaml
input_text: !include config/input_text.yaml

yeelight:
  devices:
    192.168.0.39:
      name: Living Room
      transition: 1000
      use_music_mode: true
      save_on_change: true
  custom_effects:
    - name: 'Fire Flicker'
      flow_params:
        count: 0
        transitions:
          - TemperatureTransition: [1900, 1000, 80]
          - TemperatureTransition: [1900, 2000, 60]
          - SleepTransition:       [1000]