title: Home Assistant - сервер
views:
- title: Включенный свет
  icon: mdi:home-thermometer
  cards:
  - type: glance
    title: Климат
    columns: 5
    entities:
    - entity: sensor.temperature_158d000465830c
      name: Гостиная
      icon: mdi:thermometer
    - entity: sensor.0x04cf8cdf3c8033c1_power
      name: Конвектор
    - entity: sensor.temperature_158d00049dbfda
      name: Санузел
      icon: mdi:thermometer
    - entity: sensor.temperature_158d00049dc2ee
      name: Спальня
      icon: mdi:thermometer
    - entity: sensor.temperature_158d00049fe048
      name: Улица
      icon: mdi:thermometer
    - entity: sensor.humidity_158d000465830c
      name: ""
      icon: mdi:water-percent
    - entity: sensor.0x04cf8cdf3c8033c1_energy
      name: ""
    - entity: sensor.humidity_158d00049dbfda
      name: ""
      icon: mdi:water-percent
    - entity: sensor.humidity_158d00049dc2ee
      name: ""
      icon: mdi:water-percent
    - entity: sensor.humidity_158d00049fe048
      name: ""
      icon: mdi:water-percent
  - type: history-graph
    hours_to_show: 48
    entities:
    - entity: sensor.temperature_158d000465830c
      name: Гостиная
    - entity: sensor.temperature_158d00049dbfda
      name: Санузел
    - entity: sensor.temperature_158d00049dc2ee
      name: Спальня
    - entity: sensor.0x04cf8cdf3c8033c1_power
      name: Конвектор
    - entity: sensor.humidity_158d000465830c
      name: Гостиная
    - entity: sensor.humidity_158d00049dbfda
      name: Санузел
    - entity: sensor.humidity_158d00049dc2ee
      name: Спальня
  - type: entity-filter
    entities:
      - light.megad1_p7
      - light.megad1_p8
      - light.megad1_p9
      - light.megad1_p10
      - light.megad1_p11
      - light.megad1_p12
      - light.megad1_p13
#          - light.megad1_p22
      - light.megad1_p23
#          - light.megad1_p24
      - light.megad1_p25
      - light.megad1_p26
      - light.megad1_p27
      - light.megad1_p28
      - light.megad2_p7
#          - light.megad2_p8
#          - light.megad2_p9
      - light.megad2_p10
      - light.megad2_p11
      - light.megad2_p12
      - light.megad2_p13
      - light.megad2_p22
#          - light.megad2_p23
      - light.megad2_p24
      - light.megad2_p25
      - light.megad2_p26
      - light.megad2_p27
#          - light.megad2_p28
    state_filter:
      - "on"

- title: Освещение
  icon: mdi:lightbulb-group
  cards:
  - type: markdown
    content: >
      **Освещение**
  - type: entities
    title: Прихожая
    entities:
#        - entity: switch.megad1_p24
#          icon: mdi:outdoor-lamp
    - entity: light.megad1_p25
      icon: mdi:wall-sconce-round
    - entity: light.megad1_p7
      icon: mdi:led-strip-variant
    - entity: light.megad1_p13
      icon: mdi:wall-sconce-round
  - type: entities
    title: Кухня
    entities:
    - entity: light.megad1_p10
      icon: mdi:wall-sconce-round
    - entity: light.megad1_p8
      icon: mdi:led-strip-variant
    - entity: light.megad1_p12
      icon: mdi:wall-sconce-round
    - entity: light.megad1_p23
      icon: mdi:led-strip-variant
  - type: entities
    title: Гостиная
    entities:
    - entity: light.megad1_p27
      icon: mdi:track-light
    - entity: light.megad1_p9
      icon: mdi:led-strip-variant
#        - entity: light.megad1_p22
#          icon: mdi:coach-lamp
    - entity: light.megad1_p28
      icon: mdi:globe-light
  - type: entities
    title: Санузел
    entities:
    - entity: light.megad2_p13
      icon: mdi:wall-sconce-round
    - entity: light.megad2_p7
      icon: mdi:led-strip-variant
    - entity: light.megad2_p24
      icon: mdi:fan
  - type: entities
    title: Кабинет
    entities:
    - entity: light.megad2_p10
      icon: mdi:wall-sconce-round
#        - entity: light.megad2_p23
#          icon: mdi:led-strip-variant
  - type: entities
    title: Спальня
    entities:
    - entity: light.megad2_p25
      icon: mdi:wall-sconce-round
#        - entity: light.megad2_p9
#          icon: mdi:led-strip-variant
#        - entity: light.megad2_p28
#          icon: mdi:coach-lamp
    - entity: light.megad2_p27
      icon: mdi:wall-sconce-round
  - type: entities
    title: Прочее
    entities:
    - entity: light.megad2_p22
      icon: mdi:television-ambient-light
    - entity: light.megad2_p12
      icon: mdi:wall-sconce-round
    - entity: switch.0x04cf8cdf3c8033c1
      name: Конвектор
    - entity: light.xiaomi_gateway_light
      name: Xiaomi Gateway
#        - entity: light.megad2_p8
#          icon: mdi:coach-lamp

- title: Прочее
  icon: mdi:cog
  cards:
  - type: vertical-stack
    cards:
    - type: markdown
      content: >
        **Прочее**
    - type: horizontal-stack
      cards:
      - type: gauge
        name: Загрузка ОЗУ
        unit: '%'
        entity: sensor.memory_use_percent
        severity:
          green: 0
          yellow: 60
          red: 85
      - type: gauge
        name: Диск заполнен
        unit: '%'
        entity: sensor.disk_use_percent
        severity:
          green: 0
          yellow: 60
          red: 85
    - type: horizontal-stack
      cards:
      - type: entities
        entities:
        - entity: input_text.tts_syntesiser
    - type: history-graph
      title: Входная дверь
      hours_to_show: 24
      entities:
      - entity: binary_sensor.door_window_sensor_158d00044d56f1
        name: Входная дверь

- title: Погода
  icon: mdi:weather-partly-snowy-rainy
  cards:
  - type: weather-forecast
    entity: weather.home_assistant

- title: СС 2531
  icon: mdi:usb-flash-drive
  cards:
  - type: vertical-stack
    cards:
    - type: markdown
      content: >
         **Добавление устройств**
    - type: entities
      title: Добавление Zigbee устройств
      show_header_toggle: false
      entities:
      - entity: input_boolean.zigbee_permit_join
      - entity: timer.zigbee_permit_join
      - entity: sensor.bridge_state
  - type: vertical-stack
    cards:
    - type: markdown
      content: >
         **Zigbee**
    - type: entities
      title: Розетка
      show_header_toggle: false
      entities:
      - entity: switch.0x04cf8cdf3c8033c1
      - entity: sensor.0x04cf8cdf3c8033c1_power
      - entity: sensor.0x04cf8cdf3c8033c1_energy
