title: Home Assistant - сервер
views:
- title: Включенный свет
  icon: mdi:home-thermometer
  cards:
  - type: vertical-stack
    cards:
    - !include ui/weather.yaml
    - !include ui/climate_board_short.yaml
    - !include ui/light_active.yaml
    - !include ui/climate_history_short.yaml
    - !include ui/ac.yaml

- !include ui/light.yaml

- title: Прочее
  icon: mdi:cog
  cards:
  - type: vertical-stack
    cards:
    - !include ui/ac.yaml
    - type: history-graph
      title: Освещенность в гостиной
      hours_to_show: 24
      entities:
      - entity: sensor.0x54ef4410000a2a8c_illuminance_lux
        name: Освещенность в гостиной
    - type: history-graph
      title: Входная дверь
      hours_to_show: 24
      entities:
      - entity: binary_sensor.door_window_sensor_158d00044d56f1
        name: Входная дверь
    - type: history-graph
      title: Датчик движения в гардеробной
      hours_to_show: 24
      entities:
      - entity: binary_sensor.motion_sensor_158d000632d88c
        name: Датчик движения в гардеробной
    - type: markdown
      content: >
        **Прочее**
    - type: horizontal-stack
      cards:
      - type: gauge
        name: Загрузка ОЗУ
        unit: '%'
        entity: sensor.memory_use_percent
        severity:
          green: 0
          yellow: 60
          red: 85
      - type: gauge
        name: Диск заполнен
        unit: '%'
        entity: sensor.disk_use_percent
        severity:
          green: 0
          yellow: 60
          red: 85
    - type: horizontal-stack
      cards:
      - type: entities
        entities:
        - entity: input_text.tts_syntesiser

- title: СС 2531
  icon: mdi:usb-flash-drive
  cards:
  - type: vertical-stack
    cards:
    - type: markdown
      content: >
         **Добавление устройств**
    - type: entities
      title: Добавление Zigbee устройств
      show_header_toggle: false
      entities:
      - entity: input_boolean.zigbee_permit_join
      - entity: timer.zigbee_permit_join
      - entity: sensor.bridge_state
  - type: vertical-stack
    cards:
    - type: markdown
      content: >
         **Zigbee**
    - type: entities
      title: Розетка
      show_header_toggle: false
      entities:
      - entity: switch.0x04cf8cdf3c8033c1
      - entity: sensor.0x04cf8cdf3c8033c1_power
      - entity: sensor.0x04cf8cdf3c8033c1_energy
